export const dynamic = "force-dynamic";

import { notFound } from "next/navigation";
import { createAdminClient } from "@/lib/supabase/server";
import { ScoreRing, fmtDate } from "@/components/ui";
import { AppHeader } from "@/components/wallnut/app-header";
import { ReportFindings } from "@/components/report-findings";
import { ReportPreview } from "@/components/report-preview";
import type { ProofIssue } from "@/types";

export default async function ReportPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const admin = await createAdminClient();

  const select = "id, name, kind, status, current_version, slug";
  const bySlug = await admin.from("assets").select(select).eq("slug", id).maybeSingle();
  const asset = bySlug.data ?? (await admin.from("assets").select(select).eq("id", id).maybeSingle()).data;
  if (!asset) notFound();

  const { data: version } = await admin
    .from("asset_versions")
    .select("id, version, url, preview_url, preview_meta, created_at")
    .eq("asset_id", asset.id)
    .order("version", { ascending: false })
    .limit(1)
    .single();

  const { data: proof } = await admin
    .from("proofs")
    .select("id, score, status, summary, model, created_at")
    .eq("asset_version_id", version?.id ?? "")
    .maybeSingle();

  const { data: issues } = proof
    ? await admin.from("proof_issues").select("*").eq("proof_id", proof.id).order("severity", { ascending: false })
    : { data: [] };

  const sortedIssues = sortIssues((issues ?? []) as ProofIssue[]);
  const reportedAt = proof?.created_at ?? version?.created_at ?? null;

  return (
    <div className="min-h-screen bg-black text-[#fbfbfb]">
      <AppHeader />
      <main className="mx-auto flex w-full max-w-[680px] flex-col px-4 pb-12 pt-6 sm:px-6">
        <header className="mb-4">
          <div className="flex items-start justify-between gap-3">
            <h1 className="min-w-0 flex-1 text-[clamp(20px,3.5vw,28px)] font-bold leading-tight tracking-[-0.5px]">
              {asset.name}
            </h1>
            {proof ? <ScoreRing score={proof.score} size={56} /> : null}
          </div>
          {reportedAt ? (
            <p className="mt-2 text-[11px] text-[#6c6c6c]">{fmtDate(reportedAt)}</p>
          ) : null}
        </header>

        {proof?.summary ? (
          <p className="mb-4 text-[12px] leading-relaxed text-[#919191]">{proof.summary}</p>
        ) : null}

        <div className="flex flex-col gap-3">
          {sortedIssues.length > 0 ? <ReportFindings issues={sortedIssues} /> : null}

          {version?.url ? (
            <ReportPreview
              title={asset.name}
              kind={asset.kind as "image" | "pdf"}
              url={version.url}
              previewMeta={version.preview_meta as { pages: Array<{ url: string; width: number; height: number }> } | null}
              issues={sortedIssues}
            />
          ) : null}
        </div>

        <p className="mt-10 text-center text-[10px] text-[#555]">
          Generated by Wallnut · Reviews should be confirmed by a human before publishing.
        </p>
      </main>
    </div>
  );
}

function sortIssues(issues: ProofIssue[]) {
  const rank = { high: 0, medium: 1, low: 2 } as const;
  return [...issues].sort((a, b) => rank[a.severity] - rank[b.severity]);
}
