export const dynamic = "force-dynamic";

import { notFound } from "next/navigation";
import { createAdminClient } from "@/lib/supabase/server";
import { AppHeader } from "@/components/wallnut/app-header";
import { ReportFindings } from "@/components/report-findings";
import { ReportPreview } from "@/components/report-preview";
import type { ProofIssue } from "@/types";

export default async function ReportPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const admin = await createAdminClient();

  const select = "id, name, kind, status, current_version, slug";
  const bySlug = await admin.from("assets").select(select).eq("slug", id).maybeSingle();
  const asset = bySlug.data ?? (await admin.from("assets").select(select).eq("id", id).maybeSingle()).data;
  if (!asset) notFound();

  const { data: version } = await admin
    .from("asset_versions")
    .select("id, version, url, preview_url, preview_meta, created_at")
    .eq("asset_id", asset.id)
    .order("version", { ascending: false })
    .limit(1)
    .single();

  const { data: proof } = await admin
    .from("proofs")
    .select("id, score, status, summary, model, created_at")
    .eq("asset_version_id", version?.id ?? "")
    .maybeSingle();

  const { data: issues } = proof
    ? await admin.from("proof_issues").select("*").eq("proof_id", proof.id).order("severity", { ascending: false })
    : { data: [] };

  const sortedIssues = sortIssues((issues ?? []) as ProofIssue[]);
  const reportedAt = proof?.created_at ?? version?.created_at ?? null;

  return (
    <div className="flex min-h-screen flex-col bg-black text-[#fbfbfb]">
      <AppHeader />
      <main className="mx-auto flex w-full max-w-[680px] flex-1 flex-col px-4 pb-12 pt-6 sm:px-6">
        {version?.url ? (
          <ReportPreview
            title={asset.name}
            kind={asset.kind as "image" | "pdf"}
            url={version.url}
            previewMeta={version.preview_meta as { pages: Array<{ url: string; width: number; height: number }> } | null}
            issues={sortedIssues}
            reportedAt={reportedAt}
          />
        ) : null}

        <div className={version?.url ? "mt-3" : ""}>
          {sortedIssues.length > 0 ? (
            <ReportFindings issues={sortedIssues} />
          ) : (
            <article className="overflow-hidden rounded-[8px] border border-[#111111] bg-[#060606] shadow-[0_24px_36px_rgba(0,0,0,0.48)]">
              <div className="border-b border-[#111111] px-4 py-3">
                <h2 className="text-[11px] font-bold uppercase tracking-[0.12em] text-[#6c6c6c]">
                  Findings
                </h2>
              </div>
              <p className="px-4 py-3 text-[12px] leading-relaxed text-[#bdbdbd]">
                No issues found.
              </p>
            </article>
          )}
        </div>

        {proof?.summary ? (
          <div className="mt-8">
            <p className="text-[12px] leading-relaxed text-[#919191]">{proof.summary}</p>
          </div>
        ) : null}

        <p className="mt-auto pt-10 text-center text-[10px] text-[#555]">
          Generated by Wallnut · Reviews should be confirmed by a human before publishing.
        </p>
      </main>
    </div>
  );
}

function sortIssues(issues: ProofIssue[]) {
  const rank = { high: 0, medium: 1, low: 2 } as const;
  return [...issues].sort((a, b) => rank[a.severity] - rank[b.severity]);
}
