export const dynamic = "force-dynamic";

import { notFound } from "next/navigation";
import { createAdminClient } from "@/lib/supabase/server";
import { ProofBadge, ScoreRing, StatusBadge, fmtDate } from "@/components/ui";
import { AppHeader } from "@/components/wallnut/app-header";
import { ReportFindings } from "@/components/report-findings";
import { ReportPreview } from "@/components/report-preview";
import type { ProofIssue } from "@/types";

export default async function ReportPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const admin = await createAdminClient();

  const select = "id, name, kind, status, current_version, slug";
  const bySlug = await admin.from("assets").select(select).eq("slug", id).maybeSingle();
  const asset = bySlug.data ?? (await admin.from("assets").select(select).eq("id", id).maybeSingle()).data;
  if (!asset) notFound();

  const { data: version } = await admin
    .from("asset_versions")
    .select("id, version, url, preview_url, preview_meta, created_at")
    .eq("asset_id", asset.id)
    .order("version", { ascending: false })
    .limit(1)
    .single();

  const { data: proof } = await admin
    .from("proofs")
    .select("id, score, status, summary, model, created_at")
    .eq("asset_version_id", version?.id ?? "")
    .maybeSingle();

  const { data: issues } = proof
    ? await admin.from("proof_issues").select("*").eq("proof_id", proof.id).order("severity", { ascending: false })
    : { data: [] };

  const sortedIssues = sortIssues((issues ?? []) as ProofIssue[]);
  const reportedAt = proof?.created_at ?? version?.created_at ?? null;

  return (
    <div className="min-h-screen bg-black text-[#fbfbfb]">
      <AppHeader />
      <main className="mx-auto max-w-6xl px-4 pb-12 pt-6 sm:px-6">
        <header className="mb-6 flex flex-wrap items-end justify-between gap-4">
          <div className="min-w-0 flex-1">
            <h1 className="text-[clamp(24px,4vw,34px)] font-bold leading-tight tracking-[-0.72px]">
              {asset.name}
            </h1>
          </div>
          <div className="flex flex-col items-end gap-2">
            <div className="flex items-center gap-3">
              {asset.status ? <StatusBadge status={asset.status} /> : null}
              {proof ? (
                <>
                  <ProofBadge status={proof.status} />
                  <ScoreRing score={proof.score} size={72} />
                </>
              ) : null}
            </div>
            {reportedAt ? (
              <p className="text-[11px] text-[#6c6c6c]">{fmtDate(reportedAt)}</p>
            ) : null}
          </div>
        </header>

        {proof?.summary ? (
          <p className="mb-6 max-w-3xl text-[14px] leading-relaxed text-[#bdbdbd]">{proof.summary}</p>
        ) : null}

        <div
          className={
            sortedIssues.length > 0
              ? "grid items-start gap-6 lg:grid-cols-[minmax(0,1fr)_minmax(0,1.05fr)]"
              : "mx-auto max-w-3xl"
          }
        >
          {sortedIssues.length > 0 ? (
            <div className="space-y-4">
              <ReportFindings issues={sortedIssues} />
            </div>
          ) : null}

          {version?.url ? (
            <div className={sortedIssues.length > 0 ? "lg:sticky lg:top-6" : ""}>
              <ReportPreview
                title={asset.name}
                kind={asset.kind as "image" | "pdf"}
                url={version.url}
                previewMeta={version.preview_meta as { pages: Array<{ url: string; width: number; height: number }> } | null}
                issues={sortedIssues}
              />
            </div>
          ) : null}
        </div>

        <p className="mt-10 text-center text-[10px] text-[#555]">
          Generated by Wallnut · Reviews should be confirmed by a human before publishing.
        </p>
      </main>
    </div>
  );
}

function sortIssues(issues: ProofIssue[]) {
  const rank = { high: 0, medium: 1, low: 2 } as const;
  return [...issues].sort((a, b) => rank[a.severity] - rank[b.severity]);
}
