export const IPC = {
  AudioListMicrophones: 'audio:list-microphones',
  AudioListSystem: 'audio:list-system',
  CallStart: 'call:start',
  CallStop: 'call:stop',
  CallToggleListening: 'call:toggle-listening',
  CallGetState: 'call:get-state',
  CallStateEvent: 'call:state-event',
  CallTranscriptEvent: 'call:transcript-event',
  CallInterimEvent: 'call:interim-event',
  CallSuggestionEvent: 'call:suggestion-event',
  CallAskResultEvent: 'call:ask-result-event',
  CallErrorEvent: 'call:error-event',
  CallAudioLevel: 'call:audio-level',
  CallUsageEvent: 'call:usage-event',
  CallSwitchMic: 'call:switch-mic',
  CallLiveInsight: 'call:live-insight',
  CallTopicNode: 'call:topic-node',
  CallScreenFrame: 'call:screen-frame',
  AskAi: 'call:ask',
  SessionsList: 'sessions:list',
  SessionsGet: 'sessions:get',
  SessionsRemove: 'sessions:remove',
  SessionsChangedEvent: 'sessions:changed-event',
  SettingsGet: 'settings:get',
  SettingsSet: 'settings:set',
  SettingsChangedEvent: 'settings:changed-event',
  OverlayCollapse: 'overlay:collapse',
  OverlayExpand: 'overlay:expand',
  OverlaySetCollapsed: 'overlay:set-collapsed',
  OverlayHide: 'overlay:hide',
  OverlayShow: 'overlay:show',
  OverlayResizeStart: 'overlay:resize-start',
  OverlayResize: 'overlay:resize',
  OverlayResizeEnd: 'overlay:resize-end',
  OverlayIsVisible: 'overlay:is-visible',
  OverlayVisibilityEvent: 'overlay:visibility-event',
  WindowMinimize: 'window:minimize',
  WindowClose: 'window:close',
  AppQuit: 'app:quit'
} as const

export type IpcChannel = (typeof IPC)[keyof typeof IPC]

export const MIC_IPC = {
  Start: 'mic:start',
  Stop: 'mic:stop',
  List: 'mic:list',
  Started: 'mic:started',
  Stopped: 'mic:stopped',
  Devices: 'mic:devices',
  Chunk: 'mic:chunk',
  Error: 'mic:error'
} as const
